const orderStatus = Object.freeze({
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    PROCESSING: "PROCESSING",

    PARTIALLY_SHIPPED: "PARTIALLY_SHIPPED",
    OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
    DELIVERED: "DELIVERED",
    CANCELLED: "CANCELLED",
    RETURN_REQUESTED: "RETURN_REQUESTED",
    RETURNED: "RETURNED",

    FAILED: "FAILED",   
});


export default orderStatus;
